# Generated by Django 4.2.4 on 2023-08-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="register_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="주문날짜"),
        ),
    ]
